/**
 * Word bank for typing practice.
 * ~500 common English words, sorted roughly by frequency.
 *
 * To customise: add, remove, or replace words in the array below.
 */

// eslint-disable-next-line no-unused-vars
const WORDS = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
  "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
  "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
  "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
  "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
  "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
  "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
  "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
  "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
  "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
  "great", "between", "need", "large", "under", "never", "each", "right", "begin",
  "keep", "same", "always", "start", "city", "run", "school", "still", "learn",
  "plant", "cover", "food", "sun", "four", "state", "thought", "let", "world",
  "open", "live", "where", "should", "old", "long", "far", "hand", "high",
  "place", "small", "home", "read", "own", "while", "last", "might", "found",
  "ask", "men", "change", "went", "light", "kind", "off", "point", "end",
  "move", "try", "head", "stand", "turn", "every", "boy", "did", "call",
  "does", "number", "tell", "write", "real", "life", "few", "left", "late",
  "hard", "night", "along", "name", "nothing", "hour", "feel", "side", "show",
  "much", "against", "help", "line", "air", "set", "three", "play", "both",
  "house", "put", "door", "water", "room", "young", "before", "face", "close",
  "better", "through", "such", "idea", "enough", "early", "story", "body",
  "being", "seem", "later", "group", "girl", "case", "made", "thing", "eye",
  "system", "many", "part", "since", "long", "children", "company", "until",
  "program", "question", "during", "down", "very", "again", "important",
  "however", "another", "family", "rather", "around", "country", "word",
  "less", "next", "able", "often", "human", "second", "those", "level",
  "almost", "game", "business", "above", "result", "team", "moment",
  "among", "happen", "heart", "morning", "simple", "reason", "report",
  "woman", "bring", "student", "field", "area", "money", "serve",
  "power", "market", "force", "build", "hold", "ground", "develop",
  "class", "clear", "half", "plan", "book", "carry", "inside",
  "return", "decide", "interest", "reach", "north", "table", "court",
  "produce", "expect", "product", "watch", "speak", "figure", "music",
  "future", "provide", "minute", "strong", "already", "matter",
  "office", "paper", "answer", "type", "law", "cost", "process",
  "step", "price", "effort", "record", "modern", "value", "drive",
  "picture", "voice", "suggest", "model", "perhaps", "appear", "street",
  "attention", "million", "south", "natural", "summer", "window",
  "practice", "nature", "color", "general", "language", "century",
  "example", "effect", "dark", "remember", "deep", "continue",
  "problem", "action", "common", "present", "create", "letter",
  "total", "special", "control", "age", "center", "front", "past",
  "measure", "believe", "today", "course", "social", "growth",
  "space", "form", "event", "party", "rock", "wide", "season",
  "river", "rest", "remain", "care", "single", "order", "break",
  "land", "surface", "short", "view", "fire", "fish", "tree",
  "source", "bit", "art", "least", "size", "stop", "trade",
  "sit", "act", "miss", "student", "join", "offer", "rise",
  "piece", "draw", "deal", "choose", "enter", "travel", "study",
  "fall", "east", "five", "west", "pass", "add", "recent",
  "sure", "major", "seem", "several", "month", "public", "become",
  "across", "local", "follow", "include", "member", "behind", "stay",
  "walk", "raise", "base", "note", "green", "white", "though",
  "talk", "cut", "cold", "near", "blue", "animal", "ocean",
  "window", "music", "mountain", "garden", "bridge", "kitchen",
  "island", "river", "forest", "village", "silver", "golden",
  "shadow", "winter", "spring", "gentle", "energy", "spirit",
  "travel", "dream", "wonder", "silent", "bright", "orange",
  "purple", "market", "corner", "signal", "danger", "engine",
  "design", "paint", "finger", "metal", "bottle", "cloud",
  "rain", "stone", "glass", "warm", "quick", "brown", "fox",
  "jump", "over", "lazy", "dog", "calm", "storm", "wave",
  "sand", "dust", "iron", "steel", "flame", "frost", "wind",
  "thunder", "snow", "stream", "float", "climb", "crash", "flash",
  "bloom", "twist", "spark", "shift", "drift", "swing", "track",
  "blend", "charm", "grasp", "knock", "plant", "quest", "shore"
];
